import fs from 'node:fs';
import path from 'node:path';

const componentPath = path.join(process.cwd(), 'components/evaluator-reference-panel.tsx');
const cssPath = path.join(process.cwd(), 'app/globals.css');

if (!fs.existsSync(componentPath)) {
  throw new Error('PATCH14: evaluator reference panel was not generated by patch13.');
}

let component = fs.readFileSync(componentPath, 'utf8');
const startMarker = 'function ArchivePanel({ roundDay }: { roundDay: number }) {';
const endMarker = 'export function EvaluatorReferencePanel';
const start = component.indexOf(startMarker);
const end = component.indexOf(endMarker);

if (start < 0 || end < 0 || end <= start) {
  throw new Error('PATCH14: ArchivePanel boundaries were not found.');
}

const compactArchivePanel = String.raw`function ArchivePanel({ roundDay }: { roundDay: number }) {
  const [items, setItems] = useState<ArchiveItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [institutionQuery, setInstitutionQuery] = useState("");
  const [criterionId, setCriterionId] = useState("");
  const [date, setDate] = useState("");
  const [reloadKey, setReloadKey] = useState(0);
  const [preview, setPreview] = useState<ArchiveItem | null>(null);

  useEffect(() => {
    const controller = new AbortController();
    setLoading(true);
    setError("");
    fetch("/api/evaluator/archive", { cache: "no-store", signal: controller.signal })
      .then(async (response) => {
        const payload = await response.json() as { items?: ArchiveItem[]; error?: string };
        if (!response.ok) throw new Error(payload.error || "Fayllar tarixini yuklab bo‘lmadi.");
        return payload.items || [];
      })
      .then(setItems)
      .catch((reason: unknown) => {
        if (controller.signal.aborted) return;
        setError(reason instanceof Error ? reason.message : "Fayllarni yuklashda xatolik.");
      })
      .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [reloadKey]);

  const institutionNames = useMemo(() => {
    const names = new Set(items.map((item) => String(item.institutionName || "").trim()).filter(Boolean));
    return [...names].sort((a, b) => a.localeCompare(b, "uz"));
  }, [items]);

  const selectedInstitution = useMemo(() => {
    const needle = institutionQuery.trim().toLocaleLowerCase("uz");
    if (!needle) return "";
    return institutionNames.find((name) => name.toLocaleLowerCase("uz") === needle) || "";
  }, [institutionNames, institutionQuery]);

  const institutionItems = useMemo(() => {
    if (!selectedInstitution) return [];
    return items.filter((item) => item.institutionName === selectedInstitution);
  }, [items, selectedInstitution]);

  const criteria = useMemo(() => {
    const map = new Map<string, string>();
    institutionItems.forEach((item) => {
      if (item.source !== "institution_order" && item.criterionId) map.set(item.criterionId, item.criterionTitle);
    });
    return [...map.entries()].map(([id, title]) => ({ id, title })).sort((a, b) => a.title.localeCompare(b.title, "uz"));
  }, [institutionItems]);

  useEffect(() => {
    setCriterionId("");
    setDate("");
  }, [selectedInstitution]);

  const filtered = useMemo(() => {
    if (!selectedInstitution) return [];
    return institutionItems.filter((item) => {
      if (criterionId && item.criterionId !== criterionId) return false;
      if (date && normalizeDate(item) !== date) return false;
      return true;
    });
  }, [institutionItems, selectedInstitution, criterionId, date]);

  return <div className="evaluator-ref-archive evaluator-ref-archive-compact">
    <div className="evaluator-ref-section-head evaluator-ref-section-head-compact">
      <div className="evaluator-ref-title-with-icon"><FolderOpen size={20} /><div><strong>Fayllar tarixi</strong><span>Kerakli muassasani qidirib tanlang</span></div></div>
      <span className="evaluator-ref-round">{roundDay}-kunlik nazorat</span>
    </div>

    <div className="evaluator-ref-history-picker">
      <label className="evaluator-ref-search evaluator-ref-history-search"><Search size={17} /><input list="evaluator-ref-history-institutions" value={institutionQuery} onChange={(event) => setInstitutionQuery(event.target.value)} placeholder="Muassasani qidiring va tanlang..." /></label>
      <datalist id="evaluator-ref-history-institutions">{institutionNames.map((name) => <option key={name} value={name} />)}</datalist>
      {institutionQuery && <button type="button" className="evaluator-ref-history-clear" onClick={() => setInstitutionQuery("")}>Tozalash</button>}
      <button type="button" className="evaluator-ref-refresh evaluator-ref-history-refresh" onClick={() => setReloadKey((value) => value + 1)} disabled={loading} title="Tarixni yangilash"><RefreshCw size={17} className={loading ? "animate-spin" : ""} /><span>Yangilash</span></button>
    </div>

    {loading ? <div className="evaluator-ref-history-empty"><RefreshCw className="animate-spin" size={18} /> Fayllar tarixi yuklanmoqda...</div>
      : error ? <div className="evaluator-ref-state is-error evaluator-ref-history-error"><strong>Fayllar tarixi yuklanmadi</strong><span>{error}</span><button type="button" onClick={() => setReloadKey((value) => value + 1)}>Qayta urinish</button></div>
      : !selectedInstitution ? <div className="evaluator-ref-history-empty"><Building2 size={18} /><span>Muassasani qidiruvdan tanlang — fayllar tarixi faqat shunda ochiladi.</span></div>
      : <>
        <div className="evaluator-ref-history-selected">
          <div><Building2 size={18} /><span><strong>{selectedInstitution}</strong><small>{institutionItems.length} ta fayl mavjud</small></span></div>
          <div className="evaluator-ref-history-controls">
            <select value={criterionId} onChange={(event) => setCriterionId(event.target.value)} aria-label="Mezon filtri"><option value="">Barcha mezonlar</option>{criteria.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>
            <label className="evaluator-ref-date"><CalendarDays size={16} /><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label>
          </div>
        </div>

        {filtered.length === 0 ? <div className="evaluator-ref-history-empty">Tanlangan muassasa yoki filtr bo‘yicha fayl topilmadi.</div>
          : <>
            <div className="evaluator-ref-table-wrap evaluator-ref-history-table-wrap"><table className="evaluator-ref-table"><thead><tr><th>Sana</th><th>Mezon</th><th>Nazorat</th><th>Fayl</th><th>Hajm</th><th>Amal</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td>{formatDate(item)}</td><td><strong>{item.criterionTitle}</strong></td><td><span className={item.source === "institution_order" ? "evaluator-ref-chip is-order" : "evaluator-ref-chip"}>{item.roundDay ? String(item.roundDay) + "-kunlik" : item.source === "institution_order" ? "BUYRUQ" : "—"}</span></td><td><div className="evaluator-ref-file"><FileText size={17} />{cleanFilename(item.filename)}</div></td><td>{formatBytes(Number(item.sizeBytes))}</td><td><div className="evaluator-ref-actions">{canPreview(item) && <button type="button" onClick={() => setPreview(item)}><Eye size={16} /> Ko‘rish</button>}<a href={"/api/files?id=" + encodeURIComponent(item.id)}><Download size={16} /> Yuklash</a></div></td></tr>)}</tbody></table></div>
            <div className="evaluator-ref-mobile-files evaluator-ref-history-mobile-files">{filtered.map((item) => <article key={item.id}><div><strong>{item.criterionTitle}</strong></div><div className="evaluator-ref-file"><FileText size={16} />{cleanFilename(item.filename)}</div><small>{formatDate(item)} · {formatBytes(Number(item.sizeBytes))}</small><div className="evaluator-ref-actions">{canPreview(item) && <button type="button" onClick={() => setPreview(item)}><Eye size={16} /> Ko‘rish</button>}<a href={"/api/files?id=" + encodeURIComponent(item.id)}><Download size={16} /> Yuklash</a></div></article>)}</div>
          </>}
      </>}
    {preview && <FilePreviewModal file={preview as any} onClose={() => setPreview(null)} />}
  </div>;
}

`;

component = component.slice(0, start) + compactArchivePanel + component.slice(end);
fs.writeFileSync(componentPath, component, 'utf8');
console.log('PATCH14: evaluator file history is compact and opens only after institution selection.');

const cssMarker = '/* PATCH14_COMPACT_EVALUATOR_HISTORY */';
let css = fs.readFileSync(cssPath, 'utf8');
if (!css.includes(cssMarker)) {
  css += `\n\n${cssMarker}\n.evaluator-ref-archive-compact{margin:10px 14px 12px;padding:0;border-radius:12px;background:#fbfdfe}\n.evaluator-ref-section-head-compact{padding:12px 16px;min-height:52px}\n.evaluator-ref-section-head-compact .evaluator-ref-title-with-icon{gap:10px}\n.evaluator-ref-section-head-compact .evaluator-ref-title-with-icon strong{font-size:14px}\n.evaluator-ref-section-head-compact .evaluator-ref-title-with-icon span{font-size:10px}\n.evaluator-ref-history-picker{display:grid;grid-template-columns:minmax(280px,1fr) auto auto;gap:9px;align-items:center;padding:12px 16px}\n.evaluator-ref-history-search{height:40px}\n.evaluator-ref-history-clear{height:40px;padding:0 14px;border:1px solid #d7e3e9;border-radius:8px;background:#fff;color:#647a91;font-weight:700;cursor:pointer}\n.evaluator-ref-history-clear:hover{background:#f4f9fb}\n.evaluator-ref-history-refresh{height:40px;padding:0 14px;box-shadow:none}\n.evaluator-ref-history-empty{min-height:54px;display:flex;align-items:center;justify-content:center;gap:8px;padding:10px 16px;border-top:1px solid #e7eef2;color:#7c8da1;font-size:12px;text-align:center}\n.evaluator-ref-history-error{min-height:72px;margin:0;padding:10px 16px;border-top:1px solid #e7eef2}\n.evaluator-ref-history-selected{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 16px;border-top:1px solid #e7eef2;border-bottom:1px solid #e7eef2;background:#fff}\n.evaluator-ref-history-selected>div:first-child{display:flex;align-items:center;gap:9px;min-width:0;color:#0793af}\n.evaluator-ref-history-selected>div:first-child>span{display:flex;flex-direction:column;min-width:0}\n.evaluator-ref-history-selected strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;color:#304a65}\n.evaluator-ref-history-selected small{font-size:10px;color:#8b99aa}\n.evaluator-ref-history-controls{display:flex;align-items:center;gap:8px;flex:0 0 auto}\n.evaluator-ref-history-controls select{height:36px;max-width:260px;border:1px solid #d7e3e9;border-radius:8px;background:#fff;padding:0 10px;color:#425a73;outline:0;font-size:11px}\n.evaluator-ref-history-controls .evaluator-ref-date{height:36px;min-width:160px;font-size:11px}\n.evaluator-ref-history-table-wrap{max-height:320px;margin:10px 16px 12px;overflow:auto}\n.evaluator-ref-history-table-wrap .evaluator-ref-table th{position:sticky;top:0;z-index:1}\n.evaluator-ref-history-mobile-files{max-height:360px;overflow:auto;padding-bottom:12px}\n@media(max-width:900px){.evaluator-ref-history-picker{grid-template-columns:1fr auto}.evaluator-ref-history-search{grid-column:1/-1}.evaluator-ref-history-refresh span{display:none}.evaluator-ref-history-refresh{width:40px;padding:0}.evaluator-ref-history-selected{align-items:stretch;flex-direction:column}.evaluator-ref-history-controls{width:100%;display:grid;grid-template-columns:1fr 1fr}.evaluator-ref-history-controls select{max-width:none;width:100%}.evaluator-ref-history-controls .evaluator-ref-date{min-width:0;width:100%}}\n@media(max-width:580px){.evaluator-ref-archive-compact{margin:8px 10px 10px}.evaluator-ref-section-head-compact{padding:10px 12px;flex-direction:row;align-items:center}.evaluator-ref-section-head-compact .evaluator-ref-title-with-icon span{display:none}.evaluator-ref-history-picker{padding:10px 12px}.evaluator-ref-history-controls{grid-template-columns:1fr}.evaluator-ref-history-table-wrap{margin:8px 12px 10px}.evaluator-ref-history-empty{padding:9px 12px}.evaluator-ref-history-selected{padding:9px 12px}}\n`;
  fs.writeFileSync(cssPath, css, 'utf8');
  console.log('PATCH14: compact evaluator history CSS added.');
}
