import fs from 'node:fs';

const target = 'lib/kpi-data.ts';
if (!fs.existsSync(target)) throw new Error('PATCH38: lib/kpi-data.ts not found');

let source = fs.readFileSync(target, 'utf8');

const startMarker = 'export const criteria: Criterion[] = [';
const endMarker = 'export const scoreLabels = [';
const start = source.indexOf(startMarker);
const end = source.indexOf(endMarker);
if (start < 0 || end < 0 || end <= start) throw new Error('PATCH38: criteria block boundaries not found');

const criteria = [
  {"id":"p02-02","commission":"ijro","title":"2.2-mezon","detail":"2.2. Tibbiyot muassasalaridagi “fuqaro murojaatlari” xonalarini belgilangan tartibda jihozlash, fuqarolar uchun qulay sharoit yaratish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p02-03","commission":"ijro","title":"2.3-mezon","detail":"2.3. Fuqaro murojaatlarini tahlil qilish, qonunda belgilangan tartibda imkon qadar ijobiy hal qilish choralarini ko‘rish hamda haftalik va oylik muhokamalarni o‘tkazib borish tizimini joriy qilish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p02-04","commission":"ijro","title":"2.4-mezon","detail":"2.4. Ijro intizomiga qat’iy rioya qilish, kunlik monitoring tizimini yo‘lga qo‘yish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p04-04","commission":"ijro","title":"4.4-mezon","detail":"4.4. Muassasada shifokorlar faoliyatini baholash maqsadida maxsus QR-kodlar, ishonch telefonlari va murojaatlar qutilari orqali bemorlarning fikrlarini muntazam yig‘ib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p06-01","commission":"ijro","title":"6.1-mezon","detail":"6.1. Viloyat sog‘liqni saqlash boshqarmasi kadrlar bo‘limi va tuman (shahar) tibbiyot birlashmalari hamkorligida har bir shifoxona, oilaviy poliklinika va OShP kesimidagi mavjud bo‘sh (vakant) shtat birliklarini to‘liq xatlovdan o‘tkazish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p06-02","commission":"ijro","title":"6.2-mezon","detail":"6.2. Tibbiyot muassasalarida 0.25, 0.5 va 0.75 shtat birliklarida ishlayotgan xodimlarning ro‘yxatini shakllantirish, ularning ish joylari va mutaxassisliklari bo‘yicha yagona ma’lumotlar bazasini yaratish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p06-03","commission":"ijro","title":"6.3-mezon","detail":"6.3. Xodimlarning bir nechta joyda noto‘liq stavkada ishlashi amaliyotini qisqartirib, asosiy ish joyida 1.0 stavka bilan ta’minlash orqali kadrlar qo‘nimsizligining oldini olish va tibbiy xizmat sifatini oshirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},

  {"id":"p01-01","commission":"birlamchi","title":"1.1-mezon","detail":"1.1. “Kambag‘allikdan farovonlik sari” dasturi ijrosini ta’minlash. Bunda, asosiy e’tibor “og‘ir” toifadagi mahallalarga qaratilishi, Qorako‘l tumanidagi “Chekirchi” MFYda ishlarni tashkil etish, viloyat va tuman darajasidagi rahbarlarning o‘ziga biriktirilgan 5 tadan kambag‘al oila holidan har oyda kamida 2 marta xabar olishi lozim.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p01-05","commission":"birlamchi","title":"1.5-mezon","detail":"1.5. Aholini skriningdan o‘tkazish, patronaj xizmati bilan qamrash orqali kasalliklarni erta aniqlash, sog‘lomlashtirish choralarini ko‘rish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p02-01","commission":"birlamchi","title":"2.1-mezon","detail":"2.1. Hududiy tibbiyot birlashmalari rahbarlari “Og‘ir” toifadagi mahallalarda “Sayyor qabul”larni o‘tkazib, fuqarolarning tibbiyot sohasiga oid muammolarini vakolat doirasida qonuniy hal qilinishini ta’minlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p04-05","commission":"birlamchi","title":"4.5-mezon","detail":"4.5. “Dolzarb 60 kunlik strategik o‘zgarishlar” davrida har bir tuman/shaharda kamida 10 ta yuqori texnologik jarrohlik amaliyotlari shaxsan G‘ijduvon tuman sog‘liqni saqlash bo‘limi, tuman va shahar tibbiyot birlashmalari rahbarlari tashabbusi bilan amalga oshirilishini ta’minlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p05-01","commission":"birlamchi","title":"5.1-mezon","detail":"5.1. Birlamchi bo‘g‘in (OShP va OP) muassasalari orqali 40 yoshdan oshgan barcha aholi qatlami o‘rtasida arterial gipertoniya, qandli diabet va yurak ishemik kasalliklari xavf omillarini erta bosqichda aniqlash skriningini har oylik reja asosida o‘tkazish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p05-02","commission":"birlamchi","title":"5.2-mezon","detail":"5.2. Aholi o‘rtasida sog‘lom turmush tarzini targ‘ib qilish, tuz, yog‘ iste’molini kamaytirish va o‘tkir yurak-qon tomir patologiyalarining birinchi belgilari (nafas siqilishi, ko‘krak qafasida og‘riq, nutqning buzilishi) sezilganda zudlik bilan “103” ga murojaat qilish zarurligi bo‘yicha keng qamrovli tushuntirish ishlarini olib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p05-03","commission":"birlamchi","title":"5.3-mezon","detail":"5.3. Olis hududlardan viloyat markazigacha bo‘lgan 1, 2 va 3-darajali klinikalar marshrutini to‘liq ishlab chiqish hamda tizimli faoliyatini yo‘lga qo‘yish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p07-01","commission":"birlamchi","title":"7.1-mezon","detail":"7.1. Har bir OShP, OP, KTMP va TTBda biriktirilgan aholi soni hamda kasallanish ko‘rsatkichlaridan kelib chiqqan holda, kafolatlangan paketga kiruvchi dori-darmonlar va tibbiy buyumlarga bo‘lgan oylik/choraklik ehtiyojini shakllantirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p07-02","commission":"birlamchi","title":"7.2-mezon","detail":"7.2. Xarid qilingan hamda markazlashgan tartibda keltirilgan dori vositalarini TTB/ShTB va poliklinikalarga qabul qilib olish, ularning yaroqlilik muddati va sifatini qat’iy nazoratga olish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p07-03","commission":"birlamchi","title":"7.3-mezon","detail":"7.3. Kafolatlangan paket doirasidagi dorilarni kunduzgi statsionarlar, shoshilinch yordam xonalari va oilaviy shifokorlarga belgilangan normativlar asosida o‘z vaqtida yetkazib berish choralarini ko‘rish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p11-01","commission":"birlamchi","title":"11.1-mezon","detail":"11.1. Viloyat bosh mutaxassislari ishtirokida tuman va shahar markazlarida keng qamrovli sayyor chuqurlashtirilgan tibbiy ko‘riklarni tashkil etish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p11-02","commission":"birlamchi","title":"11.2-mezon","detail":"11.2. Aholi o‘rtasida noto‘g‘ri ovqatlanish, kamharakatlilik, tuz, qand va yog‘ni me’yoridan ortiq iste’mol qilish oqibatida kelib chiqadigan yurak-qon tomir, endokrin (qandli diabet) va boshqa yuqumli bo‘lmagan kasalliklarning oldini olish bo‘yicha targ‘ibot kuchaytirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p11-03","commission":"birlamchi","title":"11.3-mezon","detail":"11.3. Tuman va shahar markazlaridagi markaziy xiyobonlar, istirohat bog‘lari yoki piyodalar yo‘laklari bo‘ylab “Besh ming qadam” marafoni uchun qulay va xavfsiz masofaviy yo‘nalishlarni belgilash hamda keng jamoatchilikni jalb qilish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p11-04","commission":"birlamchi","title":"11.4-mezon","detail":"11.4. Aholining tibbiy xizmatlardan roziligini ta’minlash, joylarda mavjud muammolar, murojaatlar va e’tirozlarni bevosita mahallalarda o‘rganish, shuningdek, tuman va shahar tibbiyot birlashmalari, markaziy poliklinikalar hamda oilaviy shifokorlik punktlari faoliyati yuzasidan fuqarolarning fikrlarini tinglash maqsadida ochiq muloqotlar tashkil etish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p12-01","commission":"birlamchi","title":"12.1-mezon","detail":"12.1. Ijtimoiy reyestridagi davolanishga va jarrohlik amaliyotiga muhtoj bemorlar qo‘shimcha ro‘yxatini shakllantirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p12-02","commission":"birlamchi","title":"12.2-mezon","detail":"12.2. Viloyatda ajratilgan 671 ta kvota bo‘yicha shakllantirilgan ro‘yxat asosida operatsiyaga muhtoj bolalar, onkogematologik hamda jigar va buyrak transplantatsiyasiga muhtoj bemorlarni “vaucher” orqali shifoxalarga to‘liq yotqizib davolash choralarini ko‘rish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p12-03","commission":"birlamchi","title":"12.3-mezon","detail":"12.3. Davolash hamda sog‘lomlashtirish yuzasidan kunlik hisobotlarni boshqarmaning shtabiga topshirib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p15-01","commission":"birlamchi","title":"15.1-mezon","detail":"15.1. Aholiga ko‘rsatilayotgan xizmatlarni yaxshilash bo‘yicha viloyat davolash–profilaktika muassasalari, shahar va tuman tibbiyot birlashmalarining malakali mutaxassislarini hamda BuxDTI professor-o‘qituvchilarini kurator sifatida biriktirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p15-02","commission":"birlamchi","title":"15.2-mezon","detail":"15.2. Mazkur kuratorlarning haftada bir marotaba savolnoma asosida hududlarda o‘rganish va amaliy yordam berib borish tizimini yo‘lga qo‘yish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p15-03","commission":"birlamchi","title":"15.3-mezon","detail":"15.3. Har oy yakuni bo‘yicha hududlarda KTMP, OP, OShP va mahalla kesimida statistik ko‘rsatkichlarni tanqidiy muhokama qilib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},

  {"id":"p03-01","commission":"statsionar","title":"3.1-mezon","detail":"3.1. Barcha tibbiyot muassasalarida Doimiy faoliyatdagi hay’at (DFH) raislari rahbarligida dori vositalari va tibbiy buyumlar oylik, choraklik va yillik ehtiyojini shakllantirib, davlat xaridlari to‘g‘risidagi Qonun talablariga muvofiq xaridlarni amalga oshirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p03-02","commission":"statsionar","title":"3.2-mezon","detail":"3.2. Har bir muassasa tomonidan Sog‘liqni saqlash vazirligi tomonidan tasdiqlangan bazaviy formulary asosida shoshilinch tibbiy yordam uchun zarur bo‘lgan dori vositalari va tibbiy buyumlar ro‘yxatini qayta ko‘rib chiqish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p03-03","commission":"statsionar","title":"3.3-mezon","detail":"3.3. Bo‘limlar kesimida ayniqsa, qabul va diagnostika bo‘limlari hamda shok palatalari uchun kunlik, haftalik va bir oylik o‘rtacha sarflanish ko‘rsatkichlaridan kelib chiqib, maksimal miqdorda zaxirasini tayyorlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p04-01","commission":"statsionar","title":"4.1-mezon","detail":"4.1. Har bir bo‘lim mudiri va shifokor ish stolida Sog‘liqni saqlash vazirligi tomonidan tasdiqlangan eng so‘nggi klinik protokollar hamda diagnostika va davolash standartlarining elektron yoki bosma nusxalari mavjudligini tekshirish va to‘liq ta’minlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p04-02","commission":"statsionar","title":"4.2-mezon","detail":"4.2. Kaslxonalarda “Sifatni nazorat qilish va bemorlar xavfsizligi bo‘limi” (yoki ichki audit guruhi) faoliyatini jonlantirish hamda har bir bo‘lim uchun sifat koordinatorlarini tayinlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p04-03","commission":"statsionar","title":"4.3-mezon","detail":"4.3. Og‘ir va kasalligi murakkab bemorlarni davolashda mahalliy shifokorlar ishtirokida muntazam ravishda telemeditsina orqali respublika/viloyat markazlari bilan maslahatlashuvlar (konsiliumlar) o‘tkazish amaliyotini kengaytirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p09-01","commission":"statsionar","title":"9.1-mezon","detail":"9.1. Viloyatdagi DPMlar kesimida mahalliy sharoitda bajarilishi qiyin bo‘lgan yoki viloyat aholisi respublika/xorijga chiqib amalga oshiradigan eng dolzarb yuqori texnologik operatsiyalar yo‘nalishlarini (neyroxirurgiya, kardioxirurgiya, endoprotezlash, laparoskopik va intervensional yo‘nalishlar) tanlab olish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p09-02","commission":"statsionar","title":"9.2-mezon","detail":"9.2. Viloyatning o‘zida murakkab yuqori texnologik operatsiyalarni bajarish ko‘lamini keskin kengaytirish maqsadida mahalliy shifokorlarning kasbiy malakasini oshirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p09-03","commission":"statsionar","title":"9.3-mezon","detail":"9.3. Xorijiy davlatlarning nufuzli klinikalari yetakchi mutaxassislari bilan muzokaralar olib borish, ularning viloyatga tashrif buyurish jadvalini kelishish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p09-04","commission":"statsionar","title":"9.4-mezon","detail":"9.4. Yetakchi xorijiy mutaxassislar ishtirokida amaliy master-klasslar va qo‘shma jarrohlatlar va amaliyotlar tashkil etish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p09-05","commission":"statsionar","title":"9.5-mezon","detail":"9.5. Har bir muassasa rahbari 10 tadan yuqori texnologik operatsiyalar amalga oshirilishini yo‘lga qo‘yish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p10-01","commission":"statsionar","title":"10.1-mezon","detail":"10.1. Tumanlardan kelib tushadigan og‘ir politravma bilan og‘rigan bemorlarni 103 xizmati orqali bevosita mas’ul Politravma markaziga kechiktirmasdan yetkazib berishning qat’iy marshrutini ishlab chiqish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p10-02","commission":"statsionar","title":"10.2-mezon","detail":"10.2. Markazlarda tunu kun (24/7) faoliyat yurituvchi travmatolog, neyroxirurg, reanimatolog, xirurg va qon-tomir xirurglaridan iborat doimiy tayyor maxsus tibbiy brigadalar faoliyatini kuchaytirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p10-03","commission":"statsionar","title":"10.3-mezon","detail":"10.3. Mazkur holatlarda telemeditsina orqali malakali mutaxassislar maslahatini tashkil etish, zarur hollarda sanitariya aviatsiyasi xizmati orqali mutaxassislar maslahatini tashkil etish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p10-04","commission":"statsionar","title":"10.4-mezon","detail":"10.4. Favqulodda holatlar yuzasidan ko‘rsatilgan tibbiy xizmat to‘g‘risidagi tezkor xabarnomani zudlik bilan hamda sutkalik umumlashtirilgan ma’lumotlarni har kuni soat 08:00 gacha boshqarmaga taqdim etib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p14-01","commission":"statsionar","title":"14.1-mezon","detail":"14.1. Kasallanish, o‘lim va nogironlik ko‘rsatkichlarini yaxshilash bo‘yicha chora-tadbirlar rejasini ishlab chiqish: Onalar o‘limi; Go‘daklar o‘limi; Nogironlik; OITS bilan kasallanish; Ruhiy-asab, narkologik, sil va onkologik kasalliklar bilan kasallanish; Yuqumli kasalliklar; Kardiologik va qandli diabet bilan kasallanish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},

  {"id":"p03-04","commission":"raqam","title":"3.4-mezon","detail":"3.4. Har bir bo‘lim katta hamshirasi tomonidan har kuni soat 08:00 va 17:00 da shok palatasi va qabul bo‘limi zaxirasini monitoring qilish hamda maxsus elektron / qog‘oz jurnalda qayd qilib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p20-01","commission":"raqam","title":"20.1-mezon","detail":"20.1. 2026-yilning 6 oylik amalga oshirilgan ishlari hisoboti tahlili.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p20-02","commission":"raqam","title":"20.2-mezon","detail":"20.2. Kelgusida yil yakuniga qadar amalga oshiriladigan ustuvor vazifalar yuzasidan strategik rejalar taqdimoti va yo‘l xaritasini belgilash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p20-03","commission":"raqam","title":"20.3-mezon","detail":"20.3. Monitoring yuritish, KPI asosida rahbarlarni baholash hamda yakuniy xulosa yuzasidan sog‘liqni saqlash vazirligiga axborot kiritish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p19-01","commission":"raqam","title":"19.1-mezon","detail":"19.1. Ommaviy axborot vositalari orqali (televideniye, radio, gazeta, jurnal, ijtimoiy tarmoqlar) kasalliklar profilaktikasi, zamonaviy diagnostika va davolash hamda sog‘lom turmush tarzini targ‘ib qilish bo‘yicha media-rejalarni ishlab chiqish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p19-02","commission":"raqam","title":"19.2-mezon","detail":"19.2. Hamkor tashkilotlar (mahalla, yoshlar, xotin-qizlar, maktabgacha va maktab, oliy ta’lim, televideniye) bilan birgalikda kasalliklarni oldini olish va profilaktikasi bo‘yicha ommaviy axborot vositalari (televideniye, radio, gazeta, jurnal, ijtimoiy tarmoqlar) orqali keng yoritib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p19-03","commission":"raqam","title":"19.3-mezon","detail":"19.3. Amalga oshirilgan ishlar bo‘yicha hisobotlarni asoslari bilan boshqarmaga taqdim etib borish","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"digital-mother-child-registry","commission":"raqam","title":"Ona-bola reestri","detail":"Ona-bola restr tizimida malumorlar to`ldirilish bo`yicha nazorat","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"digital-camera-monitoring","commission":"raqam","title":"Videokuzatuv monitoringi","detail":"Videokuzatuv monitoringgi","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},

  {"id":"p01-02","commission":"moliya","title":"1.2-mezon","detail":"1.2. Tibbiyot muassasalarida obodonlashtirish ishlarini tizimli ravishda olib borish, manzarali daraxtlar va gullar ekish, sanitariya holatini nazoratga olish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p01-03","commission":"moliya","title":"1.3-mezon","detail":"1.3. Tibbiyot muassasalarida faoliyat yurituvchi ishchi-xodimlari xonadonlarida devor va darvozalarini tartibga keltirish, obodonlashtirilishini doimiy nazoratga olish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p01-04","commission":"moliya","title":"1.4-mezon","detail":"1.4. O‘zbekiston Respublikasi Mustaqilligining 35 yillik bayrami munosabati bilan shior aks ettirilgan bannerlar va davlat bayrog‘ini tibbiyot muassasalarining ko‘rinarli joyiga o‘rnatish hamda bayramni ko‘tarinki ruhda o‘tkazish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p08-01","commission":"moliya","title":"8.1-mezon","detail":"8.1. Viloyatdagi barcha davlat tibbiyot muassasalarida amaldagi qonunchilikka muvofiq, qo‘shimcha pullik tibbiy xizmatlar turlarini ko‘paytirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p08-02","commission":"moliya","title":"8.2-mezon","detail":"8.2. Tibbiyot muassasalarining moliyaviy mustaqilligi va barqarorligini ta’minlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p08-03","commission":"moliya","title":"8.3-mezon","detail":"8.3. Aholi uchun sifatli, zamonaviy va qulay servis sharoitlarini yaratish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p08-04","commission":"moliya","title":"8.4-mezon","detail":"8.4. Viloyat va tuman (shahar) darajasidagi tibbiyot muassasalarida pullik tibbiy xizmatlar kalkulyatsiyasini qayta ko‘rib chiqib, muvofiqlashtirish choralarini ko‘rish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p16-01","commission":"moliya","title":"16.1-mezon","detail":"16.1. Muassasalarining kirish darvozalari, yo‘laklar, bordyurlar, daraxtlar, palatalar va sanitariya uzellarining bugungi holatini birma-bir ko‘zdan kechirib, amaliy ishlar ko‘lamini aniqlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p16-02","commission":"moliya","title":"16.2-mezon","detail":"16.2. Oqlash va bo‘yash materiallari, standart shiorlar va bannerlar, zarur sanitariya jihozlari (sovutgich, suyuq sovun, dezinfeksiya vositalari) hamda yotoq jihozlari (choyshab, matras, krovat) bo‘yicha ehtiyojlarni hisoblab chiqish va ta’minlash manbalarini belgilash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p17-01","commission":"moliya","title":"17.1-mezon","detail":"17.1. O‘zbekiston Respublikasi Prezidentining 2025-yil 19-maydagi PF-88-son Farmoni asosida tibbiyot muassasalarining loyiha-smeta hujjatlari tayyorlanishini nazorat qilish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p17-02","commission":"moliya","title":"17.2-mezon","detail":"17.2. 80 ta tibbiyot muassasalarida olib borilayotgan qurilish-ta’mirlash ishlarining sifatli olib borilishini qat’iy nazoratga olish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p17-03","commission":"moliya","title":"17.3-mezon","detail":"17.3. Yangi qurilib, foydalanishga topshirilayotgan muassasalarni tibbiy jihozlar bilan ta’minlash uchun belgilangan tartibda Sog‘liqni saqlash vazirligiga taklif kiritish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p18-01","commission":"moliya","title":"18.1-mezon","detail":"18.1. Har bir muassasa kesimida tibbiyot muassasalarini 2026-2027-yillar kuz-qish mavsumiga tayyorlash bo‘yicha chora-tadbirlar rejasi ishlab chiqish va tasdiqlash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p18-02","commission":"moliya","title":"18.2-mezon","detail":"18.2. Rejada har bir obyekt bo‘yicha bajariladigan ishlar, ularning moliyalashtirish manbalari, ijro muddatlari va mas’ul shaxslar aniq belgilash.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p18-03","commission":"moliya","title":"18.3-mezon","detail":"18.3. Barcha qozonxonalar va isitish qozonlarini rejali ta’mirdan chiqarish, sinovdan o‘tkazish va texnik pasportlarini rasmiylashtirish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"},
  {"id":"p18-04","commission":"moliya","title":"18.4-mezon","detail":"18.4. Tibbiyot muassasalariga 2026-2027-yillar kuz-qish mavsumi uchun zarur bo‘lgan ko‘mir yoqilg‘i zaxiralarini yaratish va belgilangan tartibda sarflanishi va saqlanishini nazorat qilib borish.","deadline":"","source":"60 kunlik baholovchilar va mezonlar taqsimoti"}
];

const counts = criteria.reduce((acc, item) => {
  acc[item.commission] = (acc[item.commission] || 0) + 1;
  return acc;
}, {});
const expected = { ijro: 7, birlamchi: 20, statsionar: 16, raqam: 9, moliya: 16 };
for (const [key, value] of Object.entries(expected)) {
  if (counts[key] !== value) throw new Error(`PATCH38: ${key} criteria count ${counts[key]} != ${value}`);
}
if (criteria.length !== 68) throw new Error(`PATCH38: total criteria ${criteria.length} != 68`);

const newBlock = 'export const criteria: Criterion[] = ' + JSON.stringify(criteria, null, 2) + ';\n\n';
source = source.slice(0, start) + newBlock + source.slice(end);
source = source.replace(
  'Birlamchi tibbiy yordam — tuman va shahar tibbiyot birlashmalarida (OP va OSHP kesimida)',
  'Birlamchi tibbiy yordam — tuman va shahar tibbiyot birlashmalarida'
);

fs.writeFileSync(target, source, 'utf8');
console.log('PATCH38: uploaded 60-kunlik criteria distribution applied.');
console.log('PATCH38: evaluator counts = ' + JSON.stringify(counts));
console.log('PATCH38: scoring = each evaluator direction normalized to 20 points; 5 x 20 = 100.');
