import fs from "node:fs";

function read(file) {
  if (!fs.existsSync(file)) throw new Error("PATCH61 missing " + file);
  return fs.readFileSync(file, "utf8");
}
function write(file, source) {
  fs.writeFileSync(file, source, "utf8");
  console.log("PATCH61: " + file);
}

// 1) Keep security headers in Next config, but CSP is request-specific and is
// generated by proxy.ts with a fresh nonce. This avoids static unsafe-inline CSP.
{
  const file = "next.config.ts";
  const source = `import type { NextConfig } from "next";

const production = process.env.NODE_ENV === "production";

const securityHeaders = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Referrer-Policy", value: "no-referrer" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), usb=(), payment=(), browsing-topics=()" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
  { key: "Cross-Origin-Resource-Policy", value: "same-origin" },
  { key: "Origin-Agent-Cluster", value: "?1" },
  { key: "X-DNS-Prefetch-Control", value: "off" },
  { key: "X-Permitted-Cross-Domain-Policies", value: "none" },
  { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
  ...(production ? [{ key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains" }] : []),
];

const privateHeaders = [
  { key: "Cache-Control", value: "no-store, max-age=0, must-revalidate" },
  { key: "Pragma", value: "no-cache" },
];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  experimental: {
    proxyClientMaxBodySize: "32mb",
  },
  async headers() {
    return [
      { source: "/:path*", headers: securityHeaders },
      { source: "/api/:path*", headers: privateHeaders },
      { source: "/admin/:path*", headers: privateHeaders },
      { source: "/evaluator/:path*", headers: privateHeaders },
      { source: "/institution/:path*", headers: privateHeaders },
      { source: "/monitoring/:path*", headers: privateHeaders },
      { source: "/login", headers: privateHeaders },
    ];
  },
};

export default nextConfig;
`;
  write(file, source);
}

// 2) Strict nonce-based CSP for pages + existing same-origin CSRF checks for API writes.
// No '*' sources, no script-src unsafe-inline, no style-src unsafe-inline.
// style-src-attr remains inline-compatible for React dynamic style attributes.
{
  const file = "proxy.ts";
  const source = `import { NextResponse, type NextRequest } from "next/server";

function firstHeader(value: string | null) {
  return (value || "").split(",")[0]?.trim() || "";
}

function makeNonce() {
  return crypto.randomUUID().replaceAll("-", "");
}

function pageCsp(nonce: string) {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "object-src 'none'",
    "form-action 'self'",
    "script-src 'self' 'nonce-" + nonce + "' 'strict-dynamic'",
    "script-src-attr 'none'",
    "style-src 'self' 'nonce-" + nonce + "'",
    "style-src-attr 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self'",
    "worker-src 'self' blob:",
    "child-src 'self' blob:",
    "frame-src 'self' blob:",
    "media-src 'self' blob:",
    "manifest-src 'self'",
    "upgrade-insecure-requests",
  ].join("; ");
}

function csrfFailure(message: string) {
  return NextResponse.json(
    { error: message },
    { status: 403, headers: { "cache-control": "no-store" } },
  );
}

export function proxy(request: NextRequest) {
  const pathname = request.nextUrl.pathname;
  const method = request.method.toUpperCase();
  const isApi = pathname === "/api" || pathname.startsWith("/api/");

  // Protect state-changing API requests from cross-site submission.
  if (isApi && method !== "GET" && method !== "HEAD" && method !== "OPTIONS") {
    const fetchSite = request.headers.get("sec-fetch-site");
    if (fetchSite && fetchSite !== "same-origin" && fetchSite !== "none") {
      return csrfFailure("Xavfsizlik siyosati: boshqa saytdan yuborilgan so‘rov bloklandi.");
    }

    const origin = request.headers.get("origin");
    if (origin) {
      const host = firstHeader(request.headers.get("x-forwarded-host")) || firstHeader(request.headers.get("host"));
      const proto = firstHeader(request.headers.get("x-forwarded-proto")) || request.nextUrl.protocol.replace(":", "") || "https";
      if (!host || origin !== proto + "://" + host) {
        return csrfFailure("Xavfsizlik siyosati: Origin mos kelmadi.");
      }
    }
  }

  // API JSON responses do not need a document CSP.
  if (isApi) return NextResponse.next();

  const nonce = makeNonce();
  const csp = pageCsp(nonce);
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);
  requestHeaders.set("Content-Security-Policy", csp);

  const response = NextResponse.next({
    request: { headers: requestHeaders },
  });
  response.headers.set("Content-Security-Policy", csp);
  return response;
}

export const config = {
  matcher: [
    {
      source: "/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)",
      missing: [
        { type: "header", key: "next-router-prefetch" },
        { type: "header", key: "purpose", value: "prefetch" },
      ],
    },
  ],
};
`;
  write(file, source);
}

// 3) Nonce CSP requires dynamic rendering so every document request receives
// a fresh nonce that Next.js can propagate to framework scripts/styles.
{
  const file = "app/layout.tsx";
  let s = read(file);
  if (s.includes('"use client"') || s.includes("'use client'")) {
    throw new Error("PATCH61: root layout is a client component; nonce CSP needs a server layout");
  }
  if (!s.includes('export const dynamic = "force-dynamic";')) {
    s += '\n\nexport const dynamic = "force-dynamic";\n';
  }
  write(file, s);
}

// 4) Never silently fall back to a public/default pepper in production.
{
  const file = "lib/server-auth.ts";
  let s = read(file);
  const from = 'export function privacyDigest(value: string) {\n  const pepper = process.env.SECURITY_PEPPER || "kpi-development-security-pepper";\n  return createHmac("sha256", pepper).update(value, "utf8").digest("hex");\n}';
  const to = 'export function privacyDigest(value: string) {\n  const configured = process.env.SECURITY_PEPPER;\n  if (process.env.NODE_ENV === "production" && (!configured || configured.length < 32)) {\n    throw new Error("SECURITY_PEPPER must be configured with at least 32 characters in production.");\n  }\n  const pepper = configured || "kpi-development-security-pepper";\n  return createHmac("sha256", pepper).update(value, "utf8").digest("hex");\n}';
  if (s.includes(from)) s = s.replace(from, to);
  else if (!s.includes("SECURITY_PEPPER must be configured")) throw new Error("PATCH61 privacyDigest anchor missing");
  write(file, s);
}

// 5) Use the last proxy-added X-Forwarded-For address instead of trusting the
// first user-supplied entry, strengthening login throttling against spoofing.
{
  const file = "app/api/auth/login/route.ts";
  let s = read(file);
  const from = '  const forwarded = request.headers.get("x-forwarded-for") || "";\n  const value = forwarded.split(",")[0]?.trim() || request.headers.get("x-real-ip")?.trim() || "unknown";';
  const to = '  const forwarded = request.headers.get("x-forwarded-for") || "";\n  const forwardedParts = forwarded.split(",").map((part) => part.trim()).filter(Boolean);\n  const value = forwardedParts.at(-1) || request.headers.get("x-real-ip")?.trim() || "unknown";';
  if (s.includes(from)) s = s.replace(from, to);
  else if (!s.includes("forwardedParts.at(-1)")) throw new Error("PATCH61 clientIp anchor missing");
  write(file, s);
}

console.log("PATCH61 SECURITY: strict nonce CSP, wildcard sources removed, CSRF preserved, stronger headers, required production pepper, safer login IP throttling.");
